export const GET_GAMES_LIST = "GET_GAMES_LIST";
export const GET_GAMES_FOR_CURRENT_PAGE = "GET_GAMES_FOR_CURRENT_PAGE";
export const FETCH_GAMES_START = "FETCH_GAMES_START";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FOR_CURRENT_PAGE_SUCCESS =
  "FETCH_GAMES_FOR_CURRENT_PAGE";
export const FETCH_GAMES_FAIL = "FETCH_GAMES_FAIL";
